# Generated by Django 4.2.4 on 2023-08-13 15:12

from django.db import migrations, models
import main.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=32)),
                ('github_link', models.TextField(max_length=64)),
                ('linkedin_link', models.TextField(max_length=64)),
                ('profile_pic', models.ImageField(upload_to=main.utils.developer_profile_pic_path)),
            ],
        ),
    ]
