# Generated by Django 4.2.4 on 2023-08-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='github_link',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='developer',
            name='linkedin_link',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='developer',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
