# Generated by Django 4.2.4 on 2023-08-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_developer_github_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='timestamp',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
