# Generated by Django 4.2.4 on 2023-08-14 11:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_developer_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='email',
            field=models.CharField(default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
    ]
